### ISSUE TITLE
persistence is not done properly

### ISSUE THREAD

**Issue by andrewchen5678** [Schluggi/helm-charts#33]
There are multiple issues with `persistence:` under the `charts/librechat/values.yaml` file:

- `persistence: ` is declared twice with conflicting values, one without comments and another with comments.
- it is only used on charts/librechat/templates/pvc.yaml in a broken way such as `existingClaim` is not being used anywhere.
- nothing else in the chart is referring to the pvc, which makes it useless.

It looks like a copy and paste from another project like meilisearch but forgot to finish adapting it for libre chat

**Comment by Schluggi** [comment]
Thanks for noticing. I forked it from [here](https://gitlab.com/menardorama/librechat-helm) including this bug.

`persistence` will be removed in 1.2.2. Since all important data is stored in a database, its persistence anyway.

**Comment by andrewchen5678** [comment]
/images and /logs should still be persisted according to the original docker compose file.

**Comment by Schluggi** [comment]
Thank you for noticing (again). Now it should implement correctly.
